#!/bin/bash

# install other required applications
sudo pacman -Syu --noconfirm $(cat "$HOME/.config/yadm/pkgs" | xargs)

# enable system-wide services
sudo ln -s /etc/sv/dbus /var/service
sudo ln -s /etc/sv/seatd /var/service
sudo ln -s /etc/sv/pipewire /var/service
sudo ln -s /etc/sv/tlp /var/service
sudo ln -s /etc/sv/wpa_supplicant /var/service
sudo ln -s /etc/sv/dhcpcd /var/service
sudo ln -s /etc/sv/cronie /var/service
sudo ln -s /etc/sv/bluetoothd /var/service

# by default, enable all user services
mkdir -p $HOME/service
ln -s $HOME/.config/sv/* $HOME/service/

# install fisher
fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"

# install z
fish -c "fisher install jethrokuan/z"

# install fzf
fish -c "fisher install jethrokuan/fzf"

# install packer.nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# pokemon colorscripts
mkdir -p $HOME/downloads
cd $HOME/downloads
git clone https://gitlab.com/phoneybadger/pokemon-colorscripts.git
cd pokemon-colorscripts
sudo ./install.sh


# install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
