#!/usr/bin/env bash
files=(~/.local/share/wallpapers/*)
wallpaper=${files[$RANDOM % ${#files[@]}]}
awww img $wallpaper --transition-type=wave --transition-duration 1 --resize crop
wal -i $wallpaper -n


