[general]
import = ["/home/wuz/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 14

[font.normal]
family = "Hack"
style = "Regular"

[window]
opacity = 0.9

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\r"
